
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c 'rm -fr ./.swirl && python swirl.py setup &&
        mkdir -p static/api/config &&
        /usr/bin/jq ".default" ./config-swirl-demo.db.json | sed -e "s/<msal-app-id>/$MSAL_APP_ID/" \
            -e "s/<msal-tenant-id>/$MSAL_TENANT_ID/" \
            -e "s/<msal-port>/$MSAL_CB_PORT/" \
            -e "s/<msal-host>/$MSAL_HOST/" > static/api/config/default &&
        python swirl.py start celery-worker celery-beats &&
        daphne -b 0.0.0.0 -p 8000 swirl_server.asgi:application'

    environment:
      - MSAL_CB_PORT=${MSAL_CB_PORT}
      - MSAL_HOST=${MSAL_HOST}
      - MSAL_APP_ID=${MSAL_APP_ID}
      - MSAL_TENANT_ID=${MSAL_TENANT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis
    expose:
      - 6379
