name: LatestSpyglassDockerBuild

on:
  workflow_run:
    workflows: [IntegrationAPITests]
    types: 
      - completed
  workflow_dispatch:

# For debugging
# on:
#   push:
#     branches: ''

jobs:

  build:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
    - name: Download branch and run_id artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: unit-tests.yml
        name: branch-info-${{ github.event_name == 'workflow_run' && github.event.workflow_run.id || github.run_id }}
      continue-on-error: true # Allow the step to fail without stopping the workflow
    - name: Determine branch for checkout
      id: determine_branch
      run: |
        if [[ -f branch.txt && -f run_id.txt ]]; then
          echo "branch=$(cat branch.txt)" >> $GITHUB_ENV
          echo "original_run_id=$(cat run_id.txt)" >> $GITHUB_ENV
        else
          BRANCH_NAME=$(echo $GITHUB_REF | cut -d "/" -f 3)
          echo "branch=$BRANCH_NAME" >> $GITHUB_ENV
        fi
    - name: Print branch to be checked out
      run: |
        echo "Branch to checkout: ${{ env.branch }}"
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.branch }}
    - name: Build the Docker image
      run: docker build --no-cache -t swirlai/spyglass:latest  -f Dockerfile.spg .
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push swirlai/spyglass
