name: PREVIEW Spyglass Docker Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# For debugging
# on:
#   push:
#     branches: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Diagnostics
      run: |
        docker system df
    - name: Host System Diagnostics
      run: |
        df -h
        du -sh *
    - name: Docker Cleanup
      run: |
        docker system prune -af
        docker volume prune -f
        docker builder prune -f
    - name: Build the Docker Image
      run: docker build --no-cache -t swirlai/spyglass:preview  -f Dockerfile.develop.spg .
    - name: Push the Docker Image
      run: docker push swirlai/spyglass:preview
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
