name: Transfer images into ACR for offer preparation

# Build a multi-arch docker image for Swirl
# comment to start build

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Environment Variables
      run: |
        echo "SWR_VERSION=9.0.$(( $(echo ${{ github.run_number }}) + 26 ))" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: pull and tag SWO
      run: |
        docker pull swirlai/swirl-search:latest
        docker tag swirlai/swirl-search:latest dnswo90.azurecr.io/swirl:${{ env.SWR_VERSION }}
        docker tag swirlai/swirl-search:latest dnswo90.azurecr.io/swirl:latest

    - name: login to acr swirl open and push
      run: |
        echo "${{ secrets.ACR_SWR_PW }}" | docker login dnswo90.azurecr.io -u "${{ secrets.ACR_SWR_USER }}" --password-stdin
        docker push dnswo90.azurecr.io/swirl:${{ env.SWR_VERSION }}
        docker push dnswo90.azurecr.io/swirl:latest

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
