name: RegressionTests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
            python-version: '3.12'
            cache: 'pip' # caching pip stuff
    - name: Install Swirl
      run: ./install.sh
    - name: Update apt
      run: sudo apt -o Acquire::Retries=3 update
    - name: Upgrade Ubuntu to latest patches
      run: sudo apt upgrade -y
    - name: Install redis-server
      run: sudo apt install -y redis-server
    - name: Set up Swirl
      run: python swirl.py setup
    - name: Start Swirl
      run: python swirl.py start

    - name: Checkout the QA Repo
      uses: actions/checkout@v4
      with:
        repository: 'swirlai/swirl-search-qa'
        token: ${{ secrets.QA_TEST_REPO_TOKEN }} # Make sure this token has the correct permissions
        path: swirl-search-qa
    - name: Run Regression Tests
      working-directory: ./path/to/directory
      run: |
        pip install -r requirements.txt --no-cache-dir
        behave --no-capture --verbose

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
