name: Security Testing Build

# Build a multi-arch docker image for testing security updates to Swirl

on:
  # push:
  #   # Trigger this workflow on pushes to the following branches
  #   branches:
  #     - security-testing
  # Allows manual run of this workflow from the Actions tab (on any branch)
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Diagnostics
      run: |
        docker system df
    - name: Host System Diagnostics
      run: |
        df -h
        du -sh *
    - name: Docker Cleanup
      run: |
        docker system prune -af
        docker volume prune -f
        docker builder prune -f
    - name: Builder Bootstrap
      run: docker buildx create --name devBuilder --use --bootstrap
    - name: Build the Docker Image
      run: docker buildx build -t swirlai/swirl-search:security-testing --platform linux/amd64,linux/arm64 --push .
    - name: Upload Log Files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
