name: SmokeTests

on:
  workflow_run:
    workflows: [UnitTests]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
    - name: Download branch artifact using dawidd6's action
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: UnitTests.yml
        name: branch-info-${{ github.event.workflow_run.id }}
    - name: Read branch from file
      id: read_branch
      run: |
        echo "::set-output name=branch::$(cat branch.txt)"
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.read_branch.outputs.branch }}
    - name: Print checked out branch
      if: github.event_name == 'workflow_run'
      run: |
        echo "Checked out branch: ${{ steps.read_branch.outputs.branch }}"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.11'
            cache: 'pip' # caching pip stuff
    - name: Run Install Swirl
      run: ./install.sh
    - name: Update apt
      run: sudo apt -o Acquire::Retries=3 update
    - name: upgrade Ubuntu to latest patches
      run: sudo apt upgrade -y
    - name: Run Install redis-server
      run: sudo apt install -y redis-server
    - name: Set up Swirl
      run: python swirl.py setup
    - name: Start up Swirl
      run: python swirl.py start
    - name: Run Smoke tests
      run: docker run --net=host -t swirlai/swirl-testing:latest-smoke-test sh -c "behave **/docker_container/*.feature --tags=docker_api_smoke"
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
