name: Testing WIP

on:
  workflow_dispatch:
    inputs:
      behave_tags:  # Input the Behave tag(s) to run
        description: 'Behave tag(s) to run'
        required: true
        default: 'estest'  # Default tag if none specified

jobs:
  wip-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup the Environment File
        run: |
          cat <<EOF > .env
          SWIRL_TEST_HOST=localhost
          MSAL_HOST=localhost
          MSAL_CB_PORT=8000
          MSAL_APP_ID=${{ secrets.QA_MSAL_APP_ID }}
          MSAL_TENANT_ID=${{ secrets.QA_MSAL_TENANT_ID }}
          QA_ADMIN_PW=${{ secrets.QA_ADMIN_PW }}
          QA_OPENAI_KEY=${{ secrets.QA_OPENAI_KEY }}
          EOF

      - name: Build and Start Application
        run: docker-compose -f docker-compose-build.yml up --build -d

      - name: Wait for Application to be Ready
        run: |
          echo "Waiting for the application to become ready..."
          max_attempts=10
          count=0
          until curl --output /dev/null --silent --head --fail http://localhost:8000/galaxy/login; do
            count=$(($count+1))
            if [ $count -ge $max_attempts ]; then
              echo "Application did not become ready in time."
              exit 1
            fi
            printf '.'
            sleep 30
          done
          echo "Application is ready."

      - name: Run the QA Suite
        run: docker run --net=host --env-file .env -t swirlai/swirl-search-qa:automated-tests-develop sh -c "behave --tags=${{ github.event.inputs.behave_tags }}"

      - name: Cleanup Application Environment
        run: docker-compose -f docker-compose-build.yml down
